trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    pip install pytest
    pip install pytest-html
    pip install requests  # Install the requests module
  displayName: 'Install dependencies'

- script: |
    pytest test/ccportal_api_automation.py --html=report.html --self-contained-html
  displayName: 'Run pytest and generate self-contained HTML report'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'report.html'
    artifactName: 'TestReport'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # SMTP configuration
      $smtpServer = "smtp.gmail.com"
      $smtpPort = 587
      $from = "susmit.s.surwade@gmail.com"
      $to = "susmit.surwade@blenheimchalcot.com"
      
      # Get today's date
      $todayDate = Get-Date -Format "yyyy-MM-dd"
      
      # Set the email subject
      $subject = "Daily API Automation report for $todayDate"

      # SMTP credentials
      $username = "susmit.s.surwade@gmail.com"
      $password = "qzod ltfm nmav tqvw"
      $organization = "susmitsurwade"
      $project = "SusmitDemo"

      # Email body
      $emailBody = "Please find the attached pytest HTML report."

      # Path to the HTML report
      $attachmentPath = "$(System.DefaultWorkingDirectory)/report.html"

      # Send email with attached HTML report
      Send-MailMessage -SmtpServer $smtpServer `
                       -Port $smtpPort `
                       -From $from `
                       -To $to `
                       -Subject $subject `
                       -Body $emailBody `
                       -Attachments $attachmentPath `
                       -Credential (New-Object System.Management.Automation.PSCredential ($username, (ConvertTo-SecureString $password -AsPlainText -Force)))
  displayName: 'Send Email with attached HTML report'