trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    pip install pytest pytest-azurepipelines
    pip install allure-pytest
  displayName: 'Install dependencies'

- script: |
    pytest test/ccportal_api_automation.py --alluredir=allure-results
  displayName: 'Run API automation tests'

- script: |
    allure generate allure-results -o allure-report --clean
  displayName: 'Generate Allure report'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'allure-report'
    artifact: 'allure-report'

- task: SendEmail@1
  inputs:
    To: 'susmit.surwade@blenheimchalcot.com'
    Subject: 'Allure Report'
    Body: 'Please find the Allure report attached.'
    Attachments: '$(System.DefaultWorkingDirectory)/allure-report'

