trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    pip install pytest pytest-azurepipelines
    pip install allure-pytest
  displayName: 'Install dependencies'

- script: |
    pytest test/ccportal_api_automation.py --alluredir=allure-results
  displayName: 'Run API automation tests'

- script: |
    allure generate allure-results -o allure-report --clean
  displayName: 'Generate Allure report'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'allure-report'
    artifact: 'allure-report'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $emailBody = "Please find the Allure report here: $(Build.Repository.Uri)/_build/results?buildId=$(Build.BuildId)"
      Send-MailMessage -SmtpServer 'your-smtp-server' -From 'sender@example.com' -To 'susmit.surwade@blenheimchalcot.com' -Subject 'Allure Report' -Body $emailBody
  displayName: 'Send Email Notification'