trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: InstallChrome@1
    inputs:
      version: 'latest'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11.7'
      addToPath: true

  - checkout: self

  - script: |
      sudo -E apt -f install -y
      sudo -E apt-get install -y wget
      sudo -E wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      sudo -E apt-get install -y google-chrome-stable
    displayName: 'Install Chrome'

  - script: |
      pip install --upgrade pip
      pip install pytest
      pip install allure-pytest
      pip install typing_extensions==4.7.1 --upgrade
      pip install selenium==4.17.0
      pip install allure-pytest
      pip install allure-python-commons==2.13.2
      pip install -U deepeval
      pip install telnetlib3
    displayName: 'Install dependencies'

  - script: |
      if [ -f "requirements.txt" ]; then
        pip install -r requirements.txt
      fi
    displayName: 'Install other dependencies'

  - script: mkdir -p reports
    displayName: 'Create reports directory'

  - script: |
      cd Tests/
      pytest --alluredir=../reports
    displayName: 'Run tests and generate allure reports'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'reports'
      artifact: 'test-reports'

  - task: SendEmail@1
    inputs:
      smtpServer: 'smtp.gmail.com'
      smtpPort: '587'
      username: '$(EMAIL_USERNAME)'
      password: '$(EMAIL_PASSWORD)'
      fromEmail: 'susmit.s.surwade@gmail.com'
      toEmail: 'susmit.s.surwade@blenheimchalcot.com'
      subject: 'Allure Report'
      body: 'Your Allure report is ready. You can access it here: https://your-domain.com/$(Build.DefinitionName)/$(Build.BuildId)/allure'
