trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    pip install pytest
    pip install pytest-html
  displayName: 'Install dependencies'

- script: |
    pytest test/ccportal_api_automation.py --html=report.html
    # Copy the CSS file to the artifact directory
    cp assets/style.css $(Build.ArtifactStagingDirectory)/
  displayName: 'Run pytest and generate HTML report'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '.'
    artifactName: 'TestReport'
