trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    pip install pytest pytest-azurepipelines
    pip install allure-pytest
    pip install requests
  displayName: 'Install dependencies'

- script: |
    pytest test/ccportal_api_automation.py --alluredir=allure-results
  displayName: 'Run API automation tests'

- script: |
    sudo apt-get update
    sudo apt-get install wget unzip -y
    wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.15.0/allure-commandline-2.15.0.zip -O allure.zip
    unzip allure.zip -d /opt
    export PATH=$PATH:/opt/allure-2.15.0/bin
    allure generate allure-results --clean -o allure-report --format html
  displayName: 'Generate Allure HTML report'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $organization = "susmitsurwade"
      $project = "SusmitDemo"
      $buildId = "$(Build.BuildId)"

      # Construct the email body with embedded HTML content
      $emailBody = @"
     <html>
     <head>
     <title>Allure Report</title>
     </head>
     <body>
     <h1>Allure Report</h1>
     <p>Please find the Allure report below:</p>
     $(Get-Content "allure-report/index.html" | Out-String)
     </body>
     </html>
     "@
      # SMTP configuration
      $smtpServer = "smtp.gmail.com"
      $smtpPort = 587
      $from = "susmit.s.surwade@gmail.com"
      $to = "susmit.surwade@blenheimchalcot.com"
      $subject = "Allure Report"

      # SMTP credentials
      $username = "susmit.s.surwade@gmail.com"
      $password = ConvertTo-SecureString "qzod ltfm nmav tqvw" -AsPlainText -Force
      $credentials = New-Object System.Management.Automation.PSCredential ($username, $password)

      # Send email with the embedded HTML content
      Send-MailMessage -SmtpServer $smtpServer -Port $smtpPort -UseSsl -From $from -To $to -Subject $subject -Body $emailBody -BodyAsHtml -Credential $credentials
displayName: 'Send Email Notification'
