trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    pip install pytest pytest-azurepipelines
    pip install allure-pytest
    pip install requests
  displayName: 'Install dependencies'

- script: |
    pytest test/ccportal_api_automation.py --alluredir=allure-results
  displayName: 'Run API automation tests'

- script: |
    sudo apt-get update
    sudo apt-get install wget unzip -y
    wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.15.0/allure-commandline-2.15.0.zip -O allure.zip
    unzip allure.zip -d /opt
    export PATH=$PATH:/opt/allure-2.15.0/bin
    allure generate allure-results --clean --single-file -o allure-report
  displayName: 'Generate Allure report'

- script: |
    allure serve allure-results > allure.txt
  displayName: 'Serve Allure report and save URL'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $organization = "susmitsurwade"
      $project = "SusmitDemo"
      $buildId = "$(Build.BuildId)"

      $url = Get-Content "allure.txt"

      $emailBody = "Please find the Allure report here: $url"

      $smtpServer = "smtp.gmail.com"
      $smtpPort = 587
      $from = "susmit.s.surwade@gmail.com"
      $to = "susmit.surwade@blenheimchalcot.com"
      $subject = "Allure Report"

      $username = "susmit.s.surwade@gmail.com"
      $password = ConvertTo-SecureString "qzod ltfm nmav tqvw" -AsPlainText -Force
      $credentials = New-Object System.Management.Automation.PSCredential ($username, $password)

      Send-MailMessage -SmtpServer $smtpServer -Port $smtpPort -UseSsl -From $from -To $to -Subject $subject -Body $emailBody -Credential $credentials
  displayName: 'Send Email Notification'