trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    pip install pytest pytest-azurepipelines
    pip install allure-pytest
    pip install requests  # Install the requests module
  displayName: 'Install dependencies'

- script: |
    pytest test/ccportal_api_automation.py --alluredir=allure-results
  displayName: 'Run API automation tests'

- script: |
    sudo apt-get update
    sudo apt-get install wget unzip -y  # Install wget and unzip
    wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.15.0/allure-commandline-2.15.0.zip -O allure.zip
    unzip allure.zip -d /opt
    export PATH=$PATH:/opt/allure-2.15.0/bin

    allure generate allure-results -o allure-report --clean
  displayName: 'Generate Allure report'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'allure-report'
    artifact: 'allure-report'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $emailBody = "Please find the Allure report here: $(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
      $smtpServer = "smtp.gmail.com"
      $smtpPort = 587
      $from = "susmit.s.surwade@gmail.com"
      $to = "susmit.surwade@blenheimchalcot.com"
      $subject = "Allure Report"
      $body = $emailBody
      
      $username = "susmit.s.surwade@gmail.com"  # Replace with your SMTP username
      $password = ConvertTo-SecureString "qzod ltfm nmav tqvw" -AsPlainText -Force  # Replace with your SMTP password
      $credentials = New-Object System.Management.Automation.PSCredential ($username, $password)
      
      Send-MailMessage -SmtpServer $smtpServer -Port $smtpPort -UseSsl -From $from -To $to -Subject $subject -Body $body -Credential $credentials
  displayName: 'Send Email Notification'

