name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openvpn
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Activate VPN connection
      run: |
        sudo openvpn --config test/azurevpnconfig_prod1.ovpn &   # Use .ovpn config file if available
        sleep 40  # Wait for the VPN connection to establish

    - name: Check Ubuntu version and install ODBC Driver 18 for SQL Server
      run: |
        if ! [[ "18.04 20.04 22.04 23.04" == *"$(lsb_release -rs)"* ]]; then
            echo "Ubuntu $(lsb_release -rs) is not currently supported."
            exit 1
        fi

        curl https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc
        curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
        sudo apt-get update
        sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18
        sudo ACCEPT_EULA=Y apt-get install -y mssql-tools18
        echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc
        source ~/.bashrc
        sudo apt-get install -y unixodbc-dev

    - name: Run tests with pytest
      run: |
        pip install pytest pytest-azurepipelines
        pytest test/flag_call_main.py
